CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    full_name       VARCHAR(255) NOT NULL,
    role            VARCHAR(50) NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX idx_app_user_username ON app_user (username);

CREATE TABLE asset (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    hostname        VARCHAR(255),
    ip_address      VARCHAR(64),
    criticality     VARCHAR(20) NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL
);

CREATE TABLE scan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    source          VARCHAR(255) NOT NULL,
    scanned_at      TIMESTAMP NOT NULL,
    asset_id        BIGINT NOT NULL,
    CONSTRAINT fk_scan_asset FOREIGN KEY (asset_id) REFERENCES asset (id)
);

CREATE TABLE finding (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id                    BIGINT NOT NULL,
    scan_id                     BIGINT,
    cve_id                      VARCHAR(50) NOT NULL,
    title                       VARCHAR(500) NOT NULL,
    description                 VARCHAR(2000),
    cvss_score                  NUMERIC(4, 2) NOT NULL,
    risk_score                  NUMERIC(5, 2),
    severity                    VARCHAR(20),
    status                      VARCHAR(30) NOT NULL,
    due_date                    DATE,
    assigned_engineer_id        BIGINT,
    accepted_risk_reason        VARCHAR(1000),
    accepted_risk_expires_at    DATE,
    escalated                   BOOLEAN NOT NULL DEFAULT FALSE,
    escalated_at                TIMESTAMP,
    duplicate_of_id             BIGINT,
    created_at                  TIMESTAMP NOT NULL,
    updated_at                  TIMESTAMP NOT NULL,
    CONSTRAINT fk_finding_asset FOREIGN KEY (asset_id) REFERENCES asset (id),
    CONSTRAINT fk_finding_scan FOREIGN KEY (scan_id) REFERENCES scan (id),
    CONSTRAINT fk_finding_engineer FOREIGN KEY (assigned_engineer_id) REFERENCES app_user (id),
    CONSTRAINT fk_finding_duplicate FOREIGN KEY (duplicate_of_id) REFERENCES finding (id)
);

CREATE INDEX idx_finding_asset_cve ON finding (asset_id, cve_id);
CREATE INDEX idx_finding_status ON finding (status);
CREATE INDEX idx_finding_severity ON finding (severity);
CREATE INDEX idx_finding_due_date ON finding (due_date);

CREATE TABLE finding_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id      BIGINT NOT NULL,
    from_status     VARCHAR(30),
    to_status       VARCHAR(30) NOT NULL,
    changed_by_id   BIGINT,
    changed_at      TIMESTAMP NOT NULL,
    note            VARCHAR(1000),
    CONSTRAINT fk_history_finding FOREIGN KEY (finding_id) REFERENCES finding (id),
    CONSTRAINT fk_history_user FOREIGN KEY (changed_by_id) REFERENCES app_user (id)
);

CREATE TABLE comment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id      BIGINT NOT NULL,
    author_id       BIGINT NOT NULL,
    content         VARCHAR(2000) NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_comment_finding FOREIGN KEY (finding_id) REFERENCES finding (id),
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES app_user (id)
);
